#
server:
  port: 9000

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    username: root
#    password: ENC(I21G78/GJ4Nux59Gz7zdKg==)

# 秘钥  不支持中文
jasypt:
  encryptor:
    password: mypasswordsalt
    poolSize: 3