server:
  port: 8087
  servlet:
    context-path: /api
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    # 连接超时时间（记得添加单位，Duration）
    timeout: 1000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 20
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    ssl: false


